/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as SortIndexRouteImport } from './app/sort/index'
import { Route as NoteIndexRouteImport } from './app/note/index'
import { Route as DashboardIndexRouteImport } from './app/dashboard/index'
import { Route as AuthIndexRouteImport } from './app/auth/index'
import { Route as NoteDocumentNameRouteImport } from './app/note/$documentName'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SortIndexRoute = SortIndexRouteImport.update({
  id: '/sort/',
  path: '/sort/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIndexRoute = NoteIndexRouteImport.update({
  id: '/note/',
  path: '/note/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteDocumentNameRoute = NoteDocumentNameRouteImport.update({
  id: '/note/$documentName',
  path: '/note/$documentName',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/note/$documentName': typeof NoteDocumentNameRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/note/': typeof NoteIndexRoute
  '/sort/': typeof SortIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/note/$documentName': typeof NoteDocumentNameRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/note': typeof NoteIndexRoute
  '/sort': typeof SortIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/note/$documentName': typeof NoteDocumentNameRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/note/': typeof NoteIndexRoute
  '/sort/': typeof SortIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/note/$documentName'
    | '/auth/'
    | '/dashboard/'
    | '/note/'
    | '/sort/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/note/$documentName'
    | '/auth'
    | '/dashboard'
    | '/note'
    | '/sort'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/note/$documentName'
    | '/auth/'
    | '/dashboard/'
    | '/note/'
    | '/sort/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoteDocumentNameRoute: typeof NoteDocumentNameRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  NoteIndexRoute: typeof NoteIndexRoute
  SortIndexRoute: typeof SortIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sort/': {
      id: '/sort/'
      path: '/sort'
      fullPath: '/sort/'
      preLoaderRoute: typeof SortIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/': {
      id: '/note/'
      path: '/note'
      fullPath: '/note/'
      preLoaderRoute: typeof NoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$documentName': {
      id: '/note/$documentName'
      path: '/note/$documentName'
      fullPath: '/note/$documentName'
      preLoaderRoute: typeof NoteDocumentNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoteDocumentNameRoute: NoteDocumentNameRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  NoteIndexRoute: NoteIndexRoute,
  SortIndexRoute: SortIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
