/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as NoteRouteRouteImport } from './app/note/route'
import { Route as IndexRouteImport } from './app/index'
import { Route as NoteIndexRouteImport } from './app/note/index'
import { Route as AuthIndexRouteImport } from './app/auth/index'
import { Route as NoteDocumentNameIndexRouteImport } from './app/note/$documentName/index'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'

const NoteRouteRoute = NoteRouteRouteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIndexRoute = NoteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoteRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteDocumentNameIndexRoute = NoteDocumentNameIndexRouteImport.update({
  id: '/$documentName/',
  path: '/$documentName/',
  getParentRoute: () => NoteRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/note': typeof NoteRouteRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/note/': typeof NoteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/note/$documentName/': typeof NoteDocumentNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/note': typeof NoteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/note/$documentName': typeof NoteDocumentNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/note': typeof NoteRouteRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/note/': typeof NoteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/note/$documentName/': typeof NoteDocumentNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/note'
    | '/auth/'
    | '/note/'
    | '/api/auth/$'
    | '/note/$documentName/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/note' | '/api/auth/$' | '/note/$documentName'
  id:
    | '__root__'
    | '/'
    | '/note'
    | '/auth/'
    | '/note/'
    | '/api/auth/$'
    | '/note/$documentName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoteRouteRoute: typeof NoteRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/note': {
      id: '/note'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof NoteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/': {
      id: '/note/'
      path: '/'
      fullPath: '/note/'
      preLoaderRoute: typeof NoteIndexRouteImport
      parentRoute: typeof NoteRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$documentName/': {
      id: '/note/$documentName/'
      path: '/$documentName'
      fullPath: '/note/$documentName/'
      preLoaderRoute: typeof NoteDocumentNameIndexRouteImport
      parentRoute: typeof NoteRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NoteRouteRouteChildren {
  NoteIndexRoute: typeof NoteIndexRoute
  NoteDocumentNameIndexRoute: typeof NoteDocumentNameIndexRoute
}

const NoteRouteRouteChildren: NoteRouteRouteChildren = {
  NoteIndexRoute: NoteIndexRoute,
  NoteDocumentNameIndexRoute: NoteDocumentNameIndexRoute,
}

const NoteRouteRouteWithChildren = NoteRouteRoute._addFileChildren(
  NoteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoteRouteRoute: NoteRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
